name: cryoem-annotator
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy>=1.23
  - scipy>=1.9
  - pandas>=1.5
  - scikit-image>=0.20
  - mrcfile>=1.4
  - dask>=2023.5
  - distributed>=2023.5
  - napari>=0.4.18
  - pyqt>=5.15
  - magicgui>=0.7
  - pyopengl>=3.1
  - ipykernel>=6.20
  - pip